import Foundation
import Observation

/// Keeps `<notes folder>/.minutes/dictionary.md`, the map AI agents read before the notes (design D10).
/// Built from front matter (`NoteIndex`) and summary types only; rewritten atomically 2 s after any of
/// them changes, whether or not a skill is installed.
@MainActor
final class NotesDictionary {
    nonisolated static let fileName = "dictionary.md"
    private static let debounce = Duration.seconds(2)

    private let index: NoteIndex
    private let summaryTypes: SummaryTypeStore
    private var pendingWrite: Task<Void, Never>?
    private var lastWritten: (folder: URL, body: String)?

    init(index: NoteIndex, summaryTypes: SummaryTypeStore) {
        self.index = index
        self.summaryTypes = summaryTypes
        observeChanges()
        scheduleWrite()
    }

    nonisolated static func url(in notesFolder: URL) -> URL {
        notesFolder.appendingPathComponent(".minutes", isDirectory: true).appendingPathComponent(fileName)
    }

    private func observeChanges() {
        withObservationTracking {
            _ = (index.notes, index.folder, summaryTypes.types)
        } onChange: { [weak self] in
            Task { @MainActor in
                self?.scheduleWrite()
                self?.observeChanges()
            }
        }
    }

    private func scheduleWrite() {
        pendingWrite?.cancel()
        pendingWrite = Task {
            try? await Task.sleep(for: Self.debounce)
            guard !Task.isCancelled else { return }
            write()
        }
    }

    /// Skips the write when nothing but the timestamp would change.
    private func write() {
        let folder = index.folder
        guard FileManager.default.fileExists(atPath: folder.path) else { return }
        let body = render()
        guard lastWritten?.folder != folder || lastWritten?.body != body else { return }
        let url = Self.url(in: folder)
        let header = "# Minutes notes dictionary\n\nLast updated: \(NoteFile.iso8601(Date())). Generated by Minutes; do not edit.\n\n"
        do {
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try Data((header + body).utf8).write(to: url, options: .atomic)
            lastWritten = (folder, body)
        } catch {
            lastWritten = nil
        }
    }

    // MARK: - Rendering

    private func render() -> String {
        let notes = index.notes
        let counts = Dictionary(notes.flatMap(\.tags).map { ($0, 1) }, uniquingKeysWith: +)
        var sections = [Self.noteFormat]
        sections.append(tagSection("Client tags", counts.filter { $0.key.hasPrefix("client/") }))
        sections.append(tagSection("Topic tags", counts.filter { !$0.key.hasPrefix("client/") }))
        sections.append("## Summary types\n\n" + summaryTypes.types.map { "- `\($0.id)`: \($0.name)" }.joined(separator: "\n") + "\n")
        sections.append("## Meetings\n\n\(notes.count) meetings, newest first.\n\n" + table(
            ["Date", "Time", "Title", "Minutes", "Tags", "File"],
            notes.map { note in
                [NoteFile.format(note.date, "yyyy-MM-dd"), NoteFile.format(note.date, "HH:mm"), note.title,
                 String(Int((note.duration / 60).rounded())), note.tags.joined(separator: ", "), note.url.lastPathComponent]
            }
        ))
        return sections.joined(separator: "\n")
    }

    /// Tags with their number of meetings, most used first.
    private func tagSection(_ title: String, _ counts: [String: Int]) -> String {
        "## \(title)\n\n" + (counts.isEmpty ? "None yet.\n" : table(
            ["Tag", "Meetings"],
            counts.sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }.map { [$0.key, String($0.value)] }
        ))
    }

    private func table(_ header: [String], _ rows: [[String]]) -> String {
        func row(_ cells: [String]) -> String {
            "| " + cells.map { $0.replacingOccurrences(of: "|", with: "\\|").replacingOccurrences(of: "\n", with: " ") }.joined(separator: " | ") + " |"
        }
        return ([row(header), row(header.map { _ in "---" })] + rows.map(row)).joined(separator: "\n") + "\n"
    }

    private static let noteFormat = """
        ## Note format

        Each meeting is one Markdown file in the notes folder. Files without `minutes_id` in their front matter were \
        not created by Minutes.

        Front matter keys:

        - `minutes_id`: the meeting's UUID
        - `title`, `date` (ISO 8601 with time zone), `duration` (seconds)
        - `speakers`: the speaker labels in the transcript
        - `tags`: client tags (`client/<name>`) and topic tags
        - `summary_type`, `summary_model`, `transcription` (the engine or model)
        - `recovered`: true when the meeting was saved after Minutes quit unexpectedly
        - `audio`: the kept recording, only when audio is kept
        - `calendar`, `attendees`, `meeting_link`: only when the recording matched a calendar event

        Body:

        - `# <title>`
        - `## Summary`, with the summary between `<!-- minutes:summary:start -->` and `<!-- minutes:summary:end -->`
        - `## Transcript`, one line per turn: `**[HH:MM:SS] Speaker:** text`, the time relative to the start of the meeting

        Speaker labels: `You` is the person who recorded the meeting (microphone); `Speaker 1`, `Speaker 2`… are \
        other participants in order of first appearance; `Others` is used when speakers were not separated.

        Other files: `.minutes/<minutes_id>.json` holds the transcript segments and summary history; \
        `.minutes/<minutes_id>.m4a` is the kept audio, when there is one.

        """
}
